name: 'Claim issue'

on:
  issue_comment:
    types: created

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Assign the issue'
        uses: garg3133/issue-claimer-action/bot-commands@actions_in_subdirectories
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          config-file-path: .github/config/bot-commands.json
