name: 'Bot Commands'

on:
  issue_comment:
    types: created

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Handle Bot Commands'
        uses: garg3133/issue-claimer-action/bot-commands@yaml-config
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          config-file-path: .github/config/bot-commands.json
          templates-dir-path: .github/config/templates
