name: 'Bot Commands'

on:
  issue_comment:
    types: created

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Handle Bot Commands'
        uses: garg3133/zulipbot-action/commands-action@commands-action
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          config-file-path: .github/config/commands-action.yaml
          templates-dir-path: .github/config/templates
