name: Post Pulls Action

on:
  workflow_run:
    workflows: ["Pulls Action"]
    types: completed

jobs:
  post-pulls-action-run:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Post pulls-action work
        uses: garg3133/zulipbot-action/pulls-action@main
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
