name: Pulls Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pulls-action:
    runs-on: ubuntu-latest
    steps:
      - name: Pulls Action
        uses: garg3133/zulipbot-action/pulls-action@pulls-action
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          config-file-path: .github/config/pulls-action-config.yaml
      - name: See Artifact
        run: cat artifact.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pull_artifact
          path: artifact.json